package com.notifyhub.announcement;
import com.notifyhub.auth.*; import com.notifyhub.common.PageResponse; import com.notifyhub.targeting.*; import jakarta.validation.constraints.*; import org.springframework.context.ApplicationEventPublisher; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import java.time.Instant;
@Service @Transactional public class AnnouncementService {
 private final AnnouncementRepository repo;private final UserRepository users;private final TargetingService targeting;private final ApplicationEventPublisher events; public AnnouncementService(AnnouncementRepository r,UserRepository u,TargetingService t,ApplicationEventPublisher e){repo=r;users=u;targeting=t;events=e;}
 @Transactional(readOnly=true) public PageResponse<AnnouncementDto> publicFeed(int page,int size){return PageResponse.from(repo.publicGlobal(PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"publishedAt"))).map(AnnouncementDto::from));}
 @Transactional(readOnly=true) public PageResponse<AnnouncementDto> urgent(int page,int size){return PageResponse.from(repo.urgent(PageRequest.of(page,size)).map(AnnouncementDto::from));}
 @Transactional(readOnly=true) public PageResponse<AnnouncementDto> visible(String username,int page,int size){User u=user(username);if(u.getRole()==Role.ADMIN)return PageResponse.from(repo.findAll(PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"createdAt"))).map(AnnouncementDto::from));var s=targeting.scope(u);return PageResponse.from(repo.visible(s.role(),s.departmentId(),s.branchId(),s.sectionId(),s.hostelId(),s.userId(),PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"publishedAt"))).map(AnnouncementDto::from));}
 @Transactional(readOnly=true) public PageResponse<AnnouncementDto> manage(int page,int size){return PageResponse.from(repo.findAll(PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"createdAt"))).map(AnnouncementDto::from));}
 public AnnouncementDto create(Request r,String username){Announcement a=new Announcement();apply(a,r);a.setCreatedBy(user(username));return AnnouncementDto.from(repo.save(a));}
 @Transactional(readOnly=true) public AnnouncementDto getForViewer(Long id,String username){Announcement a=get(id);User u=username==null?null:user(username);if(a.getStatus()!=AnnouncementStatus.PUBLISHED){if(u==null||u.getRole()!=Role.ADMIN)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Announcement not found.");}else if(u==null){if(a.getTargetType()!=TargetType.GLOBAL)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Announcement not found.");}else if(u.getRole()!=Role.ADMIN){var s=targeting.scope(u);if(!matches(a,s))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Announcement not found.");}return AnnouncementDto.from(a);}
 public AnnouncementDto update(Long id,Request r){Announcement a=get(id);if(a.getStatus()!=AnnouncementStatus.DRAFT)throw conflict("Only draft announcements may be edited.");apply(a,r);return AnnouncementDto.from(a);}
 public AnnouncementDto publish(Long id){Announcement a=get(id);if(a.getStatus()!=AnnouncementStatus.DRAFT)throw conflict("Only draft announcements may be published.");a.setStatus(AnnouncementStatus.PUBLISHED);a.setPublishedAt(Instant.now());events.publishEvent(new AnnouncementPublishedEvent(a.getId(),a.getTitle(),a.getContent(),a.isUrgent(),a.getTargetType(),a.getTargetDepartment()==null?null:a.getTargetDepartment().getId(),a.getTargetBranch()==null?null:a.getTargetBranch().getId(),a.getTargetSection()==null?null:a.getTargetSection().getId(),a.getTargetHostel()==null?null:a.getTargetHostel().getId(),a.getTargetUser()==null?null:a.getTargetUser().getId(),a.getTargetRole()));return AnnouncementDto.from(a);}
 public AnnouncementDto unpublish(Long id){Announcement a=get(id);if(a.getStatus()!=AnnouncementStatus.PUBLISHED)throw conflict("Only published announcements may be unpublished.");a.setStatus(AnnouncementStatus.DRAFT);a.setPublishedAt(null);return AnnouncementDto.from(a);}
 public AnnouncementDto archive(Long id){Announcement a=get(id);if(a.getStatus()==AnnouncementStatus.ARCHIVED)throw conflict("Announcement is already archived.");a.setStatus(AnnouncementStatus.ARCHIVED);return AnnouncementDto.from(a);}
 public void delete(Long id){Announcement a=get(id);if(a.getStatus()==AnnouncementStatus.PUBLISHED)throw conflict("Unpublish or archive this announcement before deleting it.");repo.delete(a);}
 private void apply(Announcement a,Request r){a.setTitle(r.title());a.setContent(r.content());a.setUrgent(r.urgent());var t=targeting.resolve(r.targetType(),r.departmentId(),r.branchId(),r.sectionId(),r.hostelId(),r.userEmail(),r.role());a.setTargetType(t.type());a.setTargetDepartment(t.department());a.setTargetBranch(t.branch());a.setTargetSection(t.section());a.setTargetHostel(t.hostel());a.setTargetUser(t.user());a.setTargetRole(t.role());}
 private boolean matches(Announcement a,com.notifyhub.targeting.TargetingService.Scope s){return a.getTargetType()==TargetType.GLOBAL||(a.getTargetType()==TargetType.ROLE&&a.getTargetRole()==s.role())||(a.getTargetType()==TargetType.DEPARTMENT&&java.util.Objects.equals(a.getTargetDepartment().getId(),s.departmentId()))||(a.getTargetType()==TargetType.BRANCH&&java.util.Objects.equals(a.getTargetBranch().getId(),s.branchId()))||(a.getTargetType()==TargetType.SECTION&&java.util.Objects.equals(a.getTargetSection().getId(),s.sectionId()))||(a.getTargetType()==TargetType.HOSTEL&&java.util.Objects.equals(a.getTargetHostel().getId(),s.hostelId()))||(a.getTargetType()==TargetType.USER&&java.util.Objects.equals(a.getTargetUser().getId(),s.userId()));}
 private Announcement get(Long id){return repo.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Announcement not found."));}private User user(String n){return users.findByUsername(n).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Unauthorized."));}private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}
 public record Request(@NotBlank @Size(max=180) String title,@NotBlank @Size(max=10000) String content,boolean urgent,@NotNull TargetType targetType,Long departmentId,Long branchId,Long sectionId,Long hostelId,String userEmail,Role role){}
 public record AnnouncementDto(Long id,String title,String content,boolean urgent,AnnouncementStatus status,TargetType targetType,Long departmentId,Long branchId,Long sectionId,Long hostelId,String userEmail,Role role,Instant publishedAt,Instant createdAt,Instant updatedAt,Long authorId){static AnnouncementDto from(Announcement a){return new AnnouncementDto(a.getId(),a.getTitle(),a.getContent(),a.isUrgent(),a.getStatus(),a.getTargetType(),a.getTargetDepartment()==null?null:a.getTargetDepartment().getId(),a.getTargetBranch()==null?null:a.getTargetBranch().getId(),a.getTargetSection()==null?null:a.getTargetSection().getId(),a.getTargetHostel()==null?null:a.getTargetHostel().getId(),a.getTargetUser()==null?null:a.getTargetUser().getEmail(),a.getTargetRole(),a.getPublishedAt(),a.getCreatedAt(),a.getUpdatedAt(),a.getCreatedBy().getId());}}
}
