package com.notifyhub.announcement;
import com.notifyhub.auth.*; import com.notifyhub.targeting.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.context.ApplicationEventPublisher; import org.springframework.web.server.ResponseStatusException; import java.util.Optional; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class AnnouncementServiceTest {
 @Mock AnnouncementRepository repo; @Mock UserRepository users; @Mock TargetingService targeting; @Mock ApplicationEventPublisher events; @Mock com.notifyhub.rbac.AuditLogRepository audit; @InjectMocks AnnouncementService service;
 @Test void draftCanPublishAndThenUnpublish(){Announcement a=new Announcement();a.setCreatedBy(author());when(repo.findById(1L)).thenReturn(Optional.of(a));assertThat(service.publish(1L).status()).isEqualTo(AnnouncementStatus.PUBLISHED);assertThat(service.unpublish(1L).status()).isEqualTo(AnnouncementStatus.DRAFT);}
 @Test void archivedAnnouncementCannotBePublished(){Announcement a=new Announcement();a.setCreatedBy(author());a.setStatus(AnnouncementStatus.ARCHIVED);when(repo.findById(1L)).thenReturn(Optional.of(a));assertThatThrownBy(()->service.publish(1L)).isInstanceOf(ResponseStatusException.class).hasMessageContaining("draft");}
 @Test void createsAsDraftWithServerAuthor(){User u=new User();u.setUsername("admin");u.setRole(Role.ADMIN);when(users.findByUsername("admin")).thenReturn(Optional.of(u));when(targeting.resolve(TargetType.GLOBAL,null,null,null,null,null,null)).thenReturn(new TargetingService.Target(TargetType.GLOBAL,null,null,null,null,null,null));when(repo.save(any())).thenAnswer(x->x.getArgument(0));var result=service.create(new AnnouncementService.Request("T","Body",false,TargetType.GLOBAL,null,null,null,null,null,null),"admin");assertThat(result.status()).isEqualTo(AnnouncementStatus.DRAFT);}
 private User author(){User u=new User();u.setRole(Role.ADMIN);return u;}
}
