package com.notifyhub.event;

import com.notifyhub.auth.User; import com.notifyhub.auth.UserRepository; import com.notifyhub.common.PageResponse; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.web.server.ResponseStatusException; import java.time.Instant;
@Service public class EventService{
 private final EventRepository repo;private final UserRepository users;public EventService(EventRepository r,UserRepository u){repo=r;users=u;}
 public PageResponse<EventDto> list(int page,int size,String department,boolean upcoming){Pageable p=PageRequest.of(page,size,Sort.by("startAt").ascending()); Instant now=Instant.now(); Page<Event>x; if(department!=null&&!department.isBlank()&&upcoming)x=repo.findByDepartmentIgnoreCaseAndStartAtGreaterThanEqual(department,now,p); else if(department!=null&&!department.isBlank())x=repo.findByDepartmentIgnoreCase(department,p); else if(upcoming)x=repo.findByStartAtGreaterThanEqual(now,p); else x=repo.findAll(p);return PageResponse.from(x.map(EventDto::from));}
 public EventDto create(EventRequest r,String user){Event e=new Event();apply(e,r);e.setCreatedBy(users.findByUsername(user).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Unauthorized.")));return EventDto.from(repo.save(e));}
 public EventDto update(Long id,EventRequest r){Event e=repo.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Event not found."));apply(e,r);return EventDto.from(repo.save(e));}
 public void delete(Long id){if(!repo.existsById(id))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Event not found.");repo.deleteById(id);}
 private void apply(Event e,EventRequest r){if(!r.endAt().isAfter(r.startAt()))throw new IllegalArgumentException("Event end time must be after start time.");e.setTitle(r.title());e.setDescription(r.description());e.setDepartment(r.department());e.setVenue(r.venue());e.setStartAt(r.startAt());e.setEndAt(r.endAt());}
 public record EventRequest(@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Size(max=180)String title,@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Size(max=10000)String description,@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Size(max=100)String department,@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Size(max=180)String venue,@jakarta.validation.constraints.NotNull Instant startAt,@jakarta.validation.constraints.NotNull Instant endAt){}
 public record EventDto(Long id,String title,String description,String department,String venue,Instant startAt,Instant endAt){static EventDto from(Event e){return new EventDto(e.getId(),e.getTitle(),e.getDescription(),e.getDepartment(),e.getVenue(),e.getStartAt(),e.getEndAt());}}
}
