"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { adminQueries, answerQuery, announcements, createAnnouncement, createEvent, deleteAnnouncement, deleteEvent, events, logout } from "@/lib/api";
import type { Announcement, CampusQuery, EventItem } from "@/types";
import { Loading, ErrorState } from "@/components/States";

export default function Dashboard(){
 const router=useRouter(); const [tab,setTab]=useState<"announcements"|"events"|"queries">("announcements");
 const [anns,setAnns]=useState<Announcement[]>([]),[evs,setEvs]=useState<EventItem[]>([]),[queries,setQueries]=useState<CampusQuery[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [a,setA]=useState({title:"",category:"Academic",department:"",content:"",urgent:false});
 const [ev,setEv]=useState({title:"",description:"",department:"",venue:"",startAt:"",endAt:""});
 const [answer,setAnswer]=useState<Record<number,string>>({});
 useEffect(()=>{if(!localStorage.getItem("notifyhub_access_token"))router.replace("/admin");else loadAll()},[]);
 async function loadAll(){try{setError("");const [aa,ee,qq]=await Promise.all([announcements({size:50}),events({size:50}),adminQueries(0,50)]);setAnns(aa.content);setEvs(ee.content);setQueries(qq.content)}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard.")}}
 async function addA(e:React.FormEvent){e.preventDefault();setBusy(true);try{await createAnnouncement(a);setA({title:"",category:"Academic",department:"",content:"",urgent:false});await loadAll()}catch(e){setError(e instanceof Error?e.message:"Unable to create announcement.")}finally{setBusy(false)}}
 async function addE(e:React.FormEvent){e.preventDefault();setBusy(true);try{await createEvent({...ev,startAt:new Date(ev.startAt).toISOString(),endAt:new Date(ev.endAt).toISOString()});setEv({title:"",description:"",department:"",venue:"",startAt:"",endAt:""});await loadAll()}catch(e){setError(e instanceof Error?e.message:"Unable to create event.")}finally{setBusy(false)}}
 async function removeA(id:number){if(!confirm("Delete this announcement?"))return;try{await deleteAnnouncement(id);await loadAll()}catch(e){setError(e instanceof Error?e.message:"Delete failed.")}}
 async function removeE(id:number){if(!confirm("Delete this event?"))return;try{await deleteEvent(id);await loadAll()}catch(e){setError(e instanceof Error?e.message:"Delete failed.")}}
 async function sendAnswer(id:number){try{await answerQuery(id,answer[id]||"");setAnswer({...answer,[id]:""});await loadAll()}catch(e){setError(e instanceof Error?e.message:"Response failed.")}}
 async function signOut(){const r=localStorage.getItem("notifyhub_refresh_token");try{if(r)await logout(r)}catch{}localStorage.clear();router.replace("/admin")}
 return <div className="admin-layout">
  <aside className="admin-side"><div className="brand" style={{color:"#fff",marginBottom:35}}><span className="brand-mark" style={{background:"#fff",color:"var(--blue)"}}>N</span>NotifyHub</div>
   <button className="side-button" onClick={()=>setTab("announcements")}>Announcements</button><button className="side-button" onClick={()=>setTab("events")}>Events</button><button className="side-button" onClick={()=>setTab("queries")}>Queries</button>
   <a href="/" style={{marginTop:30}}>← Public site</a><button className="side-button" onClick={signOut}>Sign out</button>
  </aside>
  <section className="admin-main"><div className="section-head"><div><span className="kicker">Control room</span><h2>Campus operations</h2></div><span className="muted">Signed in as {typeof window!=="undefined"?localStorage.getItem("notifyhub_username"):"admin"}</span></div>
   {error&&<ErrorState message={error}/>}
   <div className="grid grid-3" style={{marginBottom:25}}><div className="stat"><span className="eyebrow">Announcements</span><br/><b>{anns.length}</b></div><div className="stat"><span className="eyebrow">Events</span><br/><b>{evs.length}</b></div><div className="stat"><span className="eyebrow">Queries</span><br/><b>{queries.filter(q=>q.status==="PENDING").length}</b><span className="muted"> pending</span></div></div>
   {tab==="announcements"&&<><form className="card" onSubmit={addA}><h3>Publish announcement</h3><div className="grid grid-2"><input required className="input" placeholder="Title" value={a.title} onChange={e=>setA({...a,title:e.target.value})}/><input required className="input" placeholder="Department" value={a.department} onChange={e=>setA({...a,department:e.target.value})}/><input required className="input" placeholder="Category" value={a.category} onChange={e=>setA({...a,category:e.target.value})}/><label className="checkbox"><input type="checkbox" checked={a.urgent} onChange={e=>setA({...a,urgent:e.target.checked})}/> Mark as urgent</label></div><textarea required className="textarea" style={{marginTop:12}} placeholder="Announcement content" value={a.content} onChange={e=>setA({...a,content:e.target.value})}/><button className="button" style={{marginTop:12}} disabled={busy}>{busy?"Publishing…":"Publish"}</button></form>
   <div className="card" style={{marginTop:20}}><h3>Published announcements</h3><div style={{overflowX:"auto"}}><table className="admin-table"><thead><tr><th>Title</th><th>Department</th><th>Urgent</th><th>Action</th></tr></thead><tbody>{anns.map(x=><tr key={x.id}><td><b>{x.title}</b><br/><span className="muted">{x.category}</span></td><td>{x.department}</td><td>{x.urgent?"Yes":"No"}</td><td><button className="button danger" onClick={()=>removeA(x.id)}>Delete</button></td></tr>)}</tbody></table></div></div></>}
   {tab==="events"&&<><form className="card" onSubmit={addE}><h3>Create event</h3><div className="grid grid-2"><input required className="input" placeholder="Title" value={ev.title} onChange={e=>setEv({...ev,title:e.target.value})}/><input required className="input" placeholder="Department" value={ev.department} onChange={e=>setEv({...ev,department:e.target.value})}/><input required className="input" placeholder="Venue" value={ev.venue} onChange={e=>setEv({...ev,venue:e.target.value})}/><input required className="input" type="datetime-local" value={ev.startAt} onChange={e=>setEv({...ev,startAt:e.target.value})}/><input required className="input" type="datetime-local" value={ev.endAt} onChange={e=>setEv({...ev,endAt:e.target.value})}/></div><textarea required className="textarea" style={{marginTop:12}} placeholder="Description" value={ev.description} onChange={e=>setEv({...ev,description:e.target.value})}/><button className="button" style={{marginTop:12}} disabled={busy}>Create event</button></form>
   <div className="card" style={{marginTop:20}}><h3>Events</h3><div style={{overflowX:"auto"}}><table className="admin-table"><thead><tr><th>Title</th><th>Start</th><th>Venue</th><th>Action</th></tr></thead><tbody>{evs.map(x=><tr key={x.id}><td>{x.title}</td><td>{new Date(x.startAt).toLocaleString()}</td><td>{x.venue}</td><td><button className="button danger" onClick={()=>removeE(x.id)}>Delete</button></td></tr>)}</tbody></table></div></div></>}
   {tab==="queries"&&<div className="grid">{queries.map(q=><article className="card" key={q.id}><div className="card-top"><span className="eyebrow">{q.department}</span><span className={q.status==="PENDING"?"urgent-pill":"eyebrow"}>{q.status}</span></div><h3>{q.subject}</h3><p className="muted">{q.name} · {q.email}</p><p>{q.message}</p>{q.adminResponse&&<div className="countdown-row">Response: {q.adminResponse}</div>}{q.status==="PENDING"&&<><textarea className="textarea" placeholder="Write an answer…" value={answer[q.id]||""} onChange={e=>setAnswer({...answer,[q.id]:e.target.value})}/><button className="button" style={{marginTop:10}} onClick={()=>sendAnswer(q.id)}>Send response</button></>}</article>)}{!queries.length&&<Loading label="No queries found."/>}</div>}
  </section>
 </div>
}
