package com.notifyhub.rbac;

public enum PermissionKey {
    USER_INVITE, USER_EDIT, USER_DELETE,
    ANNOUNCEMENT_CREATE, ANNOUNCEMENT_DELETE,
    EVENT_CREATE, EVENT_DELETE,
    ROLE_CREATE, ROLE_ASSIGN, ROLE_EDIT, ROLE_REVOKE,
    QUERY_CREATE, QUERY_VIEW, QUERY_ANSWER
}
