package com.notifyhub.targeting;
import com.notifyhub.academicstructure.*; import com.notifyhub.auth.*; import com.notifyhub.faculty.*; import com.notifyhub.hostel.*; import com.notifyhub.student.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.web.server.ResponseStatusException;
@Service public class TargetingService {
 private final DepartmentRepository departments; private final BranchRepository branches; private final SectionRepository sections; private final StudentProfileRepository students; private final FacultyProfileRepository faculty; private final HostelRepository hostels; private final UserRepository users;
 public TargetingService(DepartmentRepository d,BranchRepository b,SectionRepository s,StudentProfileRepository sp,FacultyProfileRepository fp,HostelRepository h,UserRepository u){departments=d;branches=b;sections=s;students=sp;faculty=fp;hostels=h;users=u;}
 public Target resolve(TargetType type,Long departmentId,Long branchId,Long sectionId,Long hostelId,String userEmail,Role role){ if(type==null)throw bad("Target type is required."); Department d=null;Branch b=null;Section s=null;Hostel h=null;User u=null; switch(type){case GLOBAL->none(departmentId,branchId,sectionId,hostelId,userEmail,role);case ROLE->{none(departmentId,branchId,sectionId,hostelId,userEmail,null);if(role==null)throw bad("Role target requires a role.");}case DEPARTMENT->{none(null,branchId,sectionId,hostelId,userEmail,role);d=department(departmentId);}case BRANCH->{none(null,null,sectionId,hostelId,userEmail,role);b=branch(branchId);d=b.getDepartment();if(departmentId!=null&&!departmentId.equals(d.getId()))throw bad("Branch does not belong to selected department.");}case SECTION->{none(null,null,null,hostelId,userEmail,role);s=section(sectionId);b=s.getBranch();d=s.getDepartment();if(branchId!=null&&!branchId.equals(b.getId())||departmentId!=null&&!departmentId.equals(d.getId()))throw bad("Section does not belong to selected academic scope.");}case HOSTEL->{none(null,null,null,null,userEmail,role);h=hostel(hostelId);}case USER->{none(null,null,null,hostelId,null,role);if(userEmail==null||userEmail.isBlank())throw bad("User target requires userEmail.");u=users.findByEmailIgnoreCase(userEmail).filter(User::isActive).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Target user not found."));}}return new Target(type,d,b,s,h,u,role);}
 public Scope scope(User u){if(u.getRole()==Role.ADMIN)return new Scope(u.getRole(),null,null,null,null,u.getId());if(u.getRole()==Role.STUDENT){StudentProfile p=students.findByUserId(u.getId()).orElse(null);return p==null?new Scope(u.getRole(),null,null,null,null,u.getId()):new Scope(u.getRole(),p.getDepartment().getId(),p.getBranch().getId(),p.getSection().getId(),p.getHostel()==null?null:p.getHostel().getId(),u.getId());}FacultyProfile p=faculty.findByUserId(u.getId()).orElse(null);return new Scope(u.getRole(),p==null?null:p.getDepartment().getId(),null,null,null,u.getId());}
 private Department department(Long id){if(id==null)throw bad("Department target requires departmentId.");return departments.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Department not found."));}private Branch branch(Long id){if(id==null)throw bad("Branch target requires branchId.");return branches.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Branch not found."));}private Section section(Long id){if(id==null)throw bad("Section target requires sectionId.");return sections.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Section not found."));}private Hostel hostel(Long id){if(id==null)throw bad("Hostel target requires hostelId.");return hostels.findById(id).filter(Hostel::isActive).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Hostel not found."));}private void none(Object a,Object b,Object c,Object d,Object e,Object f){if(a!=null||b!=null||c!=null||d!=null||e!=null||f!=null)throw bad("Target contains fields invalid for its type.");}private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,m);} public record Target(TargetType type,Department department,Branch branch,Section section,Hostel hostel,User user,Role role){} public record Scope(Role role,Long departmentId,Long branchId,Long sectionId,Long hostelId,Long userId){}
}
